= Pet Sitter

This project is a collection of Spring sources used to depict certain aspects of the framework.

These code samples are designed to be used together with http://future.link[*Pivotal Certified Spring Core Developer Exam*] study guide.
Detailed instructions on how to use them can be found in the book.
Please buy the book, it will mean a lot to me. Also, feedback is welcome!

== Building and Deploying
This is a Gradle multi-module project. The *-practice projects, have tests and pieces left unimplemented so building the full project using:
----
gradle build
----
will fail.

To build the full project and skipping tests, build from the root (`pet-sitter`) directory:
----
gradle build -x test
----

To build the project and ignore failed tests so you can get your full build status with Gradle Receipt, build from the root (`pet-sitter`) directory, using the following command:
----
gradle build -Dscan --continue
----

German unicode characters here: http://javawiki.sowas.com/doku.php?id=java:unicode

