DROP TABLE P_PET IF EXISTS;

CREATE TABLE P_PET (ID BIGINT identity primary key,
  OWNER_ID BIGINT NOT NULL,
  NAME VARCHAR(50),
  AGE INTEGER,
  PET_TYPE VARCHAR (100) NOT NULL,
  RFID VARCHAR (100),
  UNIQUE (RFID));
