drop table P_USER if exists;

CREATE TABLE P_USER
(
  ID INT IDENTITY PRIMARY KEY
, FIRST_NAME VARCHAR2(50)
, USERNAME VARCHAR2(50) NOT NULL
, LAST_NAME VARCHAR2(50)
, PASSWORD VARCHAR2(50) NOT NULL
, ADDRESS VARCHAR2(100)
, EMAIL VARCHAR2(50) NOT NULL
, USER_TYPE VARCHAR2(50) NOT NULL
, UNIQUE(EMAIL)
, UNIQUE(USERNAME)
);


drop table P_PET if exists;

CREATE TABLE P_PET
(
  ID INT IDENTITY PRIMARY KEY
, OWNER VARCHAR2(50)
, PET_TYPE VARCHAR2(50)
, NAME VARCHAR2(100) NOT NULL
, AGE INT
, RFID VARCHAR2(100) NOT NULL
);
