INSERT INTO P_USER(ID, USERNAME, PASSWORD, EMAIL, USER_TYPE) VALUES (5, 'Jack', 'test', 'jack@pet.com', 'OWNER');
INSERT INTO P_USER(ID, USERNAME, PASSWORD, EMAIL, USER_TYPE) VALUES (6, 'Jill', 'test', 'jull@pet.com', 'SITTER');
INSERT INTO P_USER(ID, USERNAME, PASSWORD, EMAIL, USER_TYPE) VALUES (7, 'Damon', 'test', 'damon@pet.com', 'BOTH');
INSERT INTO P_USER(ID, USERNAME, PASSWORD, EMAIL, USER_TYPE) VALUES (8, 'Elon', 'test', 'elon@pet.com', 'SITTER');