INSERT INTO P_USER(ID, USERNAME, PASSWORD, EMAIL, USER_TYPE) VALUES (1, 'John', 'test', 'john@pet.com', 'OWNER');
INSERT INTO P_USER(ID, USERNAME, PASSWORD, EMAIL, USER_TYPE) VALUES (2, 'Mary', 'test', 'mary@pet.com', 'SITTER');
INSERT INTO P_USER(ID, USERNAME, PASSWORD, EMAIL, USER_TYPE) VALUES (3, 'Victoria', 'test', 'victoria@pet.com', 'BOTH');
INSERT INTO P_USER(ID, USERNAME, PASSWORD, EMAIL, USER_TYPE) VALUES (4, 'Johnny', 'test', 'johnny@pet.com', 'SITTER');


INSERT INTO P_PET(ID, NAME, AGE, PET_TYPE, OWNER, RFID) VALUES (1, 'Max', 10, 'DOG', 1, '1122334455');
INSERT INTO P_PET(ID, NAME, AGE, PET_TYPE, OWNER, RFID) VALUES (2, 'Mona', 2, 'CAT', 1, '1100223344');
INSERT INTO P_PET(ID, NAME, AGE, PET_TYPE, OWNER, RFID) VALUES (3, 'kiki', 2, 'BIRD', 3, '1100221144');